#pragma once
#include "engine/biology/Creature.hpp"
#include "engine/io/GameData.hpp"
#include "engine/math/Vec3.hpp"
#include "engine/world/Terrain.hpp"

#include <string>
#include <vector>

namespace tp {

// Environmental evidence a hunter can read: footprints, blood, and the
// broader clue family. Everything is generated by the simulation (movement,
// wounds) — never by a cosmetic "spawn a blood trail" timer.

enum class ClueKind {
    Footprint,
    BloodDrop,
    BloodSmear,
    BloodPool,
    Droppings,
    Bedding,
    Hair,
    DisturbedVegetation,
    FeedingSign,
    Carcass,
    CallHeard
};

enum class Gait { Walk, Trot, Run, Limp, Crawl };

struct Clue {
    ClueKind kind{ClueKind::Footprint};
    Vec3 position;
    Vec3 direction;        // travel direction for prints/splatter; zero if n/a
    double createdAtS{};
    double baseIntensity01{1.0}; // how strong the clue was when fresh
    std::string speciesId;
    // Footprint-specific detail a player can infer from:
    Gait gait{Gait::Walk};
    double printSizeCm{};
    double strideM{};
    bool injuredGait{false};
};

class EvidenceMap {
public:
    void add(Clue clue);

    [[nodiscard]] const std::vector<Clue>& clues() const { return clues_; }

    // How readable a clue currently is, in [0,1]. Ages with time; surface
    // and rain matter: mud holds prints ~3x longer than rock, rain washes
    // blood out fast. 0 = effectively gone.
    [[nodiscard]] static double readability(const Clue& clue, double nowS,
                                            SurfaceType surface,
                                            double rainIntensity01 = 0.0);

    // All clues within radius of pos whose readability is still above
    // minReadability. The terrain is needed to age each clue on its own
    // surface.
    [[nodiscard]] std::vector<const Clue*> queryNearby(
        const Vec3& pos, double radiusM, double nowS, const TerrainGrid& terrain,
        double minReadability = 0.05, double rainIntensity01 = 0.0) const;

private:
    std::vector<Clue> clues_;
};

// Emits footprints as an animal moves: one print per stride length of
// accumulated travel. Injury shows up in the evidence itself (shortened
// stride, drag marks flagged as injuredGait) so a player can read a limp
// from the ground.
class TrackEmitter {
public:
    explicit TrackEmitter(const SpeciesProfile& profile) : profile_(&profile) {}

    void update(EvidenceMap& evidence, const CreatureState& creature,
                const Vec3& position, double nowS, double dtSeconds);

private:
    const SpeciesProfile* profile_;
    double distanceSinceLastPrintM_{0.0};
    Vec3 lastPosition_;
    bool hasLastPosition_{false};
};

// Converts the wound simulation's current bleed state into ground evidence.
// Drop frequency and clue kind derive from the actual total bleed rate and
// whether any wound has an exit channel; a bedded animal pools instead.
class BloodEvidenceEmitter {
public:
    void update(EvidenceMap& evidence, const CreatureState& creature,
                const Vec3& position, bool moving, double nowS, double dtSeconds);

private:
    double bloodAccumulatorMl_{0.0};
};

[[nodiscard]] const char* toString(ClueKind k);
[[nodiscard]] const char* toString(Gait g);

// Maps a creature's mobility + speed to the gait its tracks show.
[[nodiscard]] Gait gaitFor(const CreatureState& creature, double speedMps,
                           const SpeciesProfile& profile);

} // namespace tp
